import { COLORS, TYPOGRAPHY, RADIUS, SHADOWS } from '../../../theme/tokens';

const howItWorksSection = {
  outerBox: {
    height: '300vh',
    position: 'relative',
    backgroundColor: COLORS.bgLight,
  },
  stickyPanel: {
    position: 'sticky',
    top: 0,
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    overflow: 'hidden',
  },
  innerContainer: {
    width: '100%',
    maxWidth: '1200px',
    mx: 'auto',
    px: { xs: 2, md: 6 },
    display: 'flex',
    gap: { xs: 4, md: 6 },
    alignItems: 'stretch',
    height: { md: '75vh' },
  },
  leftPane: {
    flex: '1 1 58%',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  stepCounterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
  },
  stepCounterBadge: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    bgcolor: COLORS.primarySurface,
    color: COLORS.onAccent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.8rem',
    fontWeight: 800,
    flexShrink: 0,
  },
  chip: {
    backgroundColor: COLORS.bgIconTinted,
    color: COLORS.primary,
    fontWeight: 600,
    fontSize: '0.72rem',
  },
  animatedBlock: {
    animation: 'fadeSlideUp 0.45s cubic-bezier(0.22,1,0.36,1)',
  },
  stepTitle: {
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: { xs: '1.8rem', md: '2.4rem' },
    color: COLORS.textPrimary,
    lineHeight: 1.2,
    mb: 1.5,
  },
  stepDesc: {
    color: COLORS.textSecondary,
    fontSize: '1rem',
    lineHeight: 1.75,
    maxWidth: '520px',
    mb: 2,
  },
  bulletRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.75,
    mb: 2.5,
  },
  bulletItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1,
  },
  bulletIcon: {
    fontSize: 16,
    color: COLORS.primary,
    mt: '2px',
    flexShrink: 0,
  },
  bulletText: {
    fontSize: '0.88rem',
    color: COLORS.textSecondary,
  },
  badgesRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
  },
  badge: {
    px: 1.5,
    py: 0.5,
    borderRadius: '20px',
    border: `1.5px solid ${COLORS.primaryAlpha35}`,
    fontSize: '0.78rem',
    fontWeight: 600,
    color: COLORS.primary,
    bgcolor: COLORS.bgWhite,
  },
  illustrationPanel: {
    flex: 1,
    borderRadius: '16px',
    bgcolor: COLORS.bgWhite,
    border: `1px solid rgba(26,26,24,0.08)`,
    boxShadow: SHADOWS.lg,
    overflow: 'hidden',
    animation: 'fadeSlideUp 0.5s cubic-bezier(0.22,1,0.36,1)',
    minHeight: 180,
  },
  rightPane: {
    flex: '0 0 auto',
    width: { xs: 0, md: '200px' },
    display: { xs: 'none', md: 'flex' },
    flexDirection: 'column',
    justifyContent: 'center',
    position: 'relative',
    pt: 6,
  },
  rightPaneLabel: {
    position: 'absolute',
    top: 0,
    left: 0,
    fontSize: '0.7rem',
    fontWeight: 700,
    color: COLORS.primary,
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
  },
  progressTrack: {
    position: 'absolute',
    left: 17,
    top: 'calc(10% + 48px)',
    bottom: '10%',
    width: 2,
    bgcolor: COLORS.primaryAlpha12,
    borderRadius: 2,
    overflow: 'hidden',
  },
  timelineNodeActive: (isActive: boolean, isDone: boolean) => ({
    width: 36,
    height: 36,
    borderRadius: '50%',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.4s cubic-bezier(0.34,1.56,0.64,1)',
    bgcolor: isActive || isDone ? COLORS.primary : COLORS.bgWhite,
    border: isActive || isDone ? `2px solid ${COLORS.primary}` : `2px solid ${COLORS.primaryAlpha20}`,
    boxShadow: isActive ? SHADOWS.focus : 'none',
    transform: isActive ? 'scale(1.12)' : 'scale(1)',
  }),
} as const;

export default howItWorksSection;
