import { COLORS, TYPOGRAPHY, RADIUS, SHADOWS } from '../../../theme/tokens';

const ctaBanner = {
  root: {
    py: { xs: 10, md: 14 },
    px: { xs: 2, md: 4 },
    backgroundColor: COLORS.bgWhite,
  },
  card: {
    maxWidth: '900px',
    mx: 'auto',
    borderRadius: '20px',
    backgroundColor: COLORS.bgDark,
    px: { xs: 4, md: 8 },
    py: { xs: 6, md: 8 },
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 500,
    height: 300,
    borderRadius: '50%',
    background: `radial-gradient(ellipse, ${COLORS.primaryAlpha35} 0%, transparent 70%)`,
    pointerEvents: 'none',
  },
  iconBox: {
    width: 56,
    height: 56,
    borderRadius: '14px',
    backgroundColor: 'rgba(42,92,69,0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    mx: 'auto',
    mb: 3,
    border: `1px solid ${COLORS.primaryAlpha35}`,
  },
  icon: {
    color: COLORS.primaryLight,
    fontSize: '1.6rem',
  },
  title: {
    fontFamily: TYPOGRAPHY.fontSerif,
    color: COLORS.onAccent,
    fontSize: { xs: '1.8rem', md: '2.6rem' },
    lineHeight: 1.2,
    mb: 2,
    position: 'relative',
    zIndex: 1,
  },
  titleAccent: {
    color: COLORS.primaryLight,
  },
  subtitle: {
    color: COLORS.primaryMuted,
    fontSize: TYPOGRAPHY.sizeMd,
    lineHeight: 1.75,
    maxWidth: '560px',
    mx: 'auto',
    mb: 5,
    position: 'relative',
    zIndex: 1,
  },
  buttonRow: {
    display: 'flex',
    gap: 2,
    justifyContent: 'center',
    flexWrap: 'wrap',
    position: 'relative',
    zIndex: 1,
  },
  primaryButton: {
    px: 4,
    py: 1.5,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primarySurface,
    color: COLORS.onAccent,
    fontWeight: 600,
    boxShadow: '0 8px 24px rgba(42,92,69,0.4)',
    '&:hover': {
      backgroundColor: COLORS.primarySurfaceDark,
      boxShadow: '0 12px 28px rgba(42,92,69,0.5)',
    },
    transition: 'all 0.25s ease',
  },
  outlinedButton: {
    px: 4,
    py: 1.5,
    borderRadius: RADIUS.md,
    borderColor: 'rgba(42,92,69,0.5)',
    color: COLORS.primaryMuted,
    fontWeight: 600,
    '&:hover': {
      borderColor: COLORS.primary,
      backgroundColor: COLORS.primaryAlpha12,
      color: COLORS.primaryLight,
    },
    transition: 'all 0.25s ease',
  },
  trust: {
    color: COLORS.primaryMuted,
    fontSize: '0.8rem',
    mt: 4,
    position: 'relative',
    zIndex: 1,
  },
} as const;

export default ctaBanner;
