import { COLORS, RADIUS, SHADOWS, TYPOGRAPHY } from '../../../theme/tokens';

const settings = {
  root: {
    bgcolor: COLORS.bgLight,
    minHeight: '100vh',
    py: { xs: 3, md: 6 },
    px: 2,
  },
  container: {
    maxWidth: 1080,
    mx: 'auto',
  },
  hero: {
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'center' },
    flexDirection: { xs: 'column', sm: 'row' },
    gap: 3,
    p: { xs: 3, md: 4 },
    mb: 3,
    borderRadius: RADIUS.xl,
    bgcolor: COLORS.bgWhite,
    boxShadow: SHADOWS.lg,
    border: `1px solid ${COLORS.borderLight}`,
  },
  heroName: {
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: { xs: 24, md: 28 },
    color: COLORS.textPrimary,
    lineHeight: 1.15,
  },
  heroEmail: {
    fontSize: 13,
    color: COLORS.textSecondary,
    mb: 1,
  },
  quickActions: {
    display: 'flex',
    gap: 1,
    flexWrap: 'wrap',
    mt: { xs: 1, sm: 0 },
  },
  quickBtn: {
    textTransform: 'none',
    fontWeight: 600,
    borderRadius: RADIUS.pill,
    borderColor: COLORS.borderMedium,
    color: COLORS.primary,
    px: 2,
    '&:hover': { borderColor: COLORS.primary, bgcolor: COLORS.primaryAlpha12 },
  },
  shell: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: { xs: 0, md: 3 },
  },
  sidebar: {
    display: 'flex',
    flexDirection: { xs: 'row', md: 'column' },
    gap: 0.5,
    width: { xs: '100%', md: 220 },
    flexShrink: 0,
    p: 1.5,
    mb: { xs: 2, md: 0 },
    borderRadius: RADIUS.xl,
    bgcolor: COLORS.bgWhite,
    boxShadow: SHADOWS.sm,
    border: `1px solid ${COLORS.borderLight}`,
    overflowX: { xs: 'auto', md: 'visible' },
  },
  navItem: (isActive: boolean, isDanger: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    px: 2,
    py: 1.25,
    borderRadius: RADIUS.lg,
    fontSize: 14,
    fontWeight: isActive ? 600 : 500,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'background-color .12s, color .12s',
    bgcolor: isActive ? COLORS.primary : 'transparent',
    color: isDanger ? COLORS.textSecondary : isActive ? COLORS.bgWhite : COLORS.textSecondary,
    '&:hover': { bgcolor: isActive ? COLORS.primaryDark : COLORS.bgHover },
  }),
  content: {
    flex: 1,
    minWidth: 0,
    p: { xs: 2.5, md: 4 },
    borderRadius: RADIUS.xl,
    bgcolor: COLORS.bgWhite,
    boxShadow: SHADOWS.sm,
    border: `1px solid ${COLORS.borderLight}`,
  },
} as const;

export default settings;
