import { COLORS, RADIUS } from '../../../../theme/tokens';

const getStartVisualizer = {
  paper: {
    p: { xs: 3, md: 4 },
    borderRadius: '24px',
    border: `1px solid ${COLORS.borderLight}`,
    display: 'flex',
    flexDirection: 'column',
    bgcolor: 'white',
  },
  previewArea: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    mb: 3,
  },
  builderPreview: {
    py: 3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    bgcolor: COLORS.primaryAlpha12,
    borderRadius: 4,
    animation: 'fadeIn 0.5s',
  },
  grammarPreview: {
    py: 4,
    px: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    bgcolor: COLORS.primaryAlpha12,
    borderRadius: 4,
    position: 'relative',
    animation: 'fadeIn 0.5s',
  },
  fixIconBadge: {
    position: 'absolute',
    right: 20,
    top: 20,
    bgcolor: COLORS.primary,
    color: 'white',
    width: 48,
    height: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    boxShadow: '0 4px 12px rgba(42,92,69,0.3)',
  },
  analyzerPreview: {
    py: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    bgcolor: COLORS.primaryAlpha12,
    borderRadius: 4,
    position: 'relative',
    animation: 'fadeIn 0.5s',
  },
  actionButton: {
    py: 2,
    borderRadius: RADIUS.md,
    bgcolor: COLORS.primary,
    '&:hover': { bgcolor: COLORS.primaryDark, boxShadow: 'none' },
    boxShadow: 'none',
    fontWeight: 'bold',
    fontSize: '1.1rem',
  },
} as const;

export default getStartVisualizer;
