import { COLORS } from '../../../theme/tokens';

const builder = {
  root: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    bgcolor: COLORS.bgLight,
    overflow: 'hidden',
    position: 'relative',
  },
  stepperBar: {
    flex: '0 0 auto',
    px: 2,
    pt: 0.75,
    pb: 0.25,
    display: 'flex',
    justifyContent: 'center',
  },
  stepper: { width: '100%', maxWidth: 620 },
  contentRow: {
    flex: '1 1 auto',
    minHeight: 0,
    display: 'flex',
    gap: { xs: 1.5, md: 2 },
    px: { xs: 1.5, md: 2.5 },
    py: 1,
  },
  editorPane: {
    flex: '0 0 auto',
    width: 560,
    minHeight: 0,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  previewPane: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    bgcolor: COLORS.bgLight,
    borderRadius: 3,
    display: { xs: 'none', md: 'block' },
  },
  dock: {
    flex: '0 0 auto',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: { xs: 2.5, md: 4 },
    py: 0.5,
    borderTop: `1px solid ${COLORS.borderLight}`,
    bgcolor: 'white',
  },
  dockItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 0.25,
  },
  dockButton: {
    width: 44,
    height: 44,
    borderRadius: '50%',
    bgcolor: COLORS.bgLight,
    color: COLORS.primary,
    border: `1px solid ${COLORS.borderLight}`,
    '&:hover': { bgcolor: COLORS.primaryAlpha12 },
  },
  dockLabel: { fontSize: '0.63rem', color: COLORS.textSecondary, fontWeight: 600 },
  alertBar: {
    position: 'fixed',
    top: 12,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 20,
  },
  donePreview: {
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'center',
    p: { xs: 1.5, md: 2.5 },
  },
  doneBar: {
    flex: '0 0 auto',
    display: 'flex',
    justifyContent: 'center',
    gap: 2,
    py: 1.5,
    borderTop: `1px solid ${COLORS.borderLight}`,
    bgcolor: 'white',
  },
  primaryButton: {
    bgcolor: COLORS.primary,
    textTransform: 'none',
    px: 4,
    borderRadius: 2,
    boxShadow: 'none',
    '&:hover': { bgcolor: COLORS.primaryDark },
  },
  ghostButton: { textTransform: 'none', px: 3, borderRadius: 2, color: COLORS.textSecondary },
  homeButton: {
    position: 'absolute',
    left: { xs: 12, md: 24 },
    top: { xs: 8, md: 14 },
    zIndex: 100,
    bgcolor: 'white',
    border: `1px solid ${COLORS.borderLight}`,
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    color: COLORS.textSecondary,
    '&:hover': {
      bgcolor: COLORS.primaryAlpha12,
      color: COLORS.primary,
      borderColor: COLORS.primaryAlpha20,
    },
  },
} as const;

export default builder;
